openapi: "3.0.2"
info:
  title: Ganbaru Wallet
  version: "1.0"
servers:
  - url: https://julianirigoyen.github.io/ganbaru-wallet/
paths:
  $ref: "./paths/_index.yaml"
components:
  schemas:
    $ref: "./components/schemas/_index.yaml"